# kubernetes deployment file
apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      server: client-label # This is the label of the deployment

  template:
    metadata:
      labels:
        server: client-label # This is the label of the deployment
    spec:
      containers:
        - name: practice-react-client
          image: practice-react-client:v4  # docker images  | grep client
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production

