# kubernetes service file
apiVersion: v1
kind: Service

metadata:
  name: client-service

spec:
  type: ClusterIP
  selector:
    server: client-label # talk to the deployment with this label
  ports:
    - port: 80
      targetPort: 3000 # This is the port of the deployment
