# kubernetes deployment file
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      server: nginx-label # This is the label of the deployment

  template:
    metadata:
      labels:
        server: nginx-label # This is the label of the deployment
    spec:
      containers:
        - name: nginx
          image: practice-nginx:v3 # docker images  | grep nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production

