# kubernetes service file
apiVersion: v1
kind: Service

metadata:
  name: api-service

spec:
  type: ClusterIP
  selector:
    server: api-label # talk to the deployment with this label
  ports:
    - port: 80
      targetPort: 9000 # This is the port of the deployment
